### PR TITLE
Saved places

### LINKED ISSUE #63: Display Saved Places
Based on the user feedback we will display the saves places by clicking a button in the top bar.  The saved locations will then populate the map with a different color pin and the cards will be displayed as normal.

### LINKED ISSUE #73: Log out button does not work

### PR DESCRIPTION
**Pull request by emmapaczkowski**
This pull request add the ability for users to display their saved places when they click a saved places button.  closes #63 .

### CODE REVIEW

File: where-to-travel/src/main/webapp/script.js [hunk 1]
```diff
@@ -376,75 +383,134 @@ function populatePlaces(placeArray) {
...
   for(let place of placeArray) {
-    // marker creation
-    let placeMarker = new google.maps.Marker({
-      position: place.geometry.location,
-      map: map,
-      title: place.name,
-      icon: PIN_PATH,
-    });
+      console.log(place);
+    if (savedPlacesSet.has(place.place_id) && document.getElementById(place.place_id)) {
```
Comment (PriyaVarra) [inline where-to-travel/src/main/webapp/script.js:460]: Might be nice to add a comment explaining what this if-else statement is doing

File: where-to-travel/src/main/webapp/script.js [hunk 2]
```diff
@@ -376,75 +383,134 @@ function populatePlaces(placeArray) {
...
-    // For the material bootstrap library, the preferred method of dom interaction is jquery,
-    // especially for adding elements.
-    let cardElement = $(htmlContent).click(function(event) {
-      if(event.target.nodeName != 'SPAN') {
-        toggleFocusOff();
-        selectLocationMarker($(this).attr('placeName'));
-        $(this).addClass('active-card');
-       focusedCard = this;
+     // Check to see if it is a saved place, if so make the star pressed 
+      if(savedPlacesSet.has(place.place_id) === true) {
```
Comment (PriyaVarra) [inline where-to-travel/src/main/webapp/script.js]: nit:  change if statement to "if (savedPlacesSet.has(place.place_id))"

File: where-to-travel/src/main/webapp/script.js [hunk 3]
```diff
@@ -376,75 +383,134 @@ function populatePlaces(placeArray) {
...
        // Add users saved places to the real time database in Firebase when star is pressed
       const database = firebase.database();
       var uID = firebase.auth().currentUser.uid;
-      var ref = database.ref('users/' + uID + '/' + 'places' + '/' + name);
+      var ref = database.ref('users/' + uID + '/places/' + name);
       var data = {
         name: name,
-        link: link,
-        time: time,
+        timeAsString: time,
```
Comment (PriyaVarra) [inline where-to-travel/src/main/webapp/script.js:536]: It might be nice to also include timeInSeconds field like on line 851 so that the objects passed into populatePlaces are always consistent

File: where-to-travel/src/main/webapp/script.js [hunk 4]
```diff
@@ -376,75 +383,134 @@ function populatePlaces(placeArray) {
...
+        place_id: placeId,
       }
       ref.set(data);
+      addGeometry(name, placeId);
```
Comment (PriyaVarra) [inline where-to-travel/src/main/webapp/script.js]: Just curious, is it possible to add the latitude and longitude as hidden attributes in the card similar to savedPlaceId on line 541? Since they're float values I imagine it may be difficult or not even possible, but if not, it could be worth looking into to avoid additional API calls.

**Review by PriyaVarra — COMMENTED** [review]
Looks really good! Just a couple of minor style things and a question.

File: where-to-travel/src/main/webapp/script.js (hunk 1 above)
Comment (emmapaczkowski) [reply where-to-travel/src/main/webapp/script.js:460]: Good idea. will do

**Review by andy7809 — COMMENTED** [review]
After Priya's comments are addressed, LGTM!

File: where-to-travel/src/main/webapp/script.js (hunk 3 above)
Comment (emmapaczkowski) [reply where-to-travel/src/main/webapp/script.js:536]: done

File: where-to-travel/src/main/webapp/script.js (hunk 4 above)
Comment (emmapaczkowski) [reply where-to-travel/src/main/webapp/script.js]: done.  That was a good idea.

File: where-to-travel/src/main/webapp/script.js [hunk 5]
```diff
@@ -59,19 +58,29 @@ const LOGOUT_ID = 'logout';
...
 const NO_PLACES_HTML_PATH = 'noPlaces.txt';
 
+// The map display object
 let map;
+// Current user
 let user = false;
+// Current home location
 let home = null;
+// Whether the saved places should be displayed or not
+let displaySavedPlaces = false;
```
Comment (wjiamin) [inline where-to-travel/src/main/webapp/script.js]: Unused constant?

File: where-to-travel/src/main/webapp/script.js [hunk 6]
```diff
@@ -177,11 +194,13 @@ function showModal(htmlFilePath) {
     .then(content => openModal(content));
 }
 
-
+// When auth changes, display the proper dashboard
 firebase.auth().onAuthStateChanged(function(user) {
   $('#' + DASH_ID).empty();
   if (user) {
     addUserDash();
+    // When a user logs out, clear the saved plases set
```
Comment (wjiamin) [inline where-to-travel/src/main/webapp/script.js]: Clarify comment here since this doesn't seem to be the path for logged out users

File: where-to-travel/src/main/webapp/script.js [hunk 7]
```diff
@@ -348,17 +367,33 @@ function addLoginButtons() {
  */
 function addUserDash() {
   const dashElement = $(getUserDashHtml(user));
-  $(dashElement[2]).click(function () {
+  // reverse the boolean control on click
```
Comment (wjiamin) [inline where-to-travel/src/main/webapp/script.js]: For my understanding, could you clarify why we reverse the boolean control here?

File: where-to-travel/src/main/webapp/script.js [hunk 8]
```diff
@@ -447,46 +502,72 @@ function populatePlaces(placeArray) {
...
       ref.remove();
+      savedPlacesSet.delete(placeId);
     }
   });
 }
+ 
+/**
+ * Call the database and displays all saved places.
+ */
+function savedPlaces() {
```
Comment (wjiamin) [inline where-to-travel/src/main/webapp/script.js]: nit: rename to displaySavedPlaces?

File: where-to-travel/src/main/webapp/script.js [hunk 9]
```diff
@@ -414,27 +450,46 @@ function populatePlaces(placeArray) {
...
+    // there is nothing to do so coninue.
+    if (savedPlacesSet.has(place.place_id) && document.getElementById(place.place_id)) {
+      continue;
+    // If you request to display the saved places while you currently have search results being displayed,
+    // check to see if any of the saved places are already displayed, if so press the star and continue.
+    } else if (displayedPlacesSet.has(place.place_id)) {
+      let savedIcon = document.getElementById('icon' + place.name);
+      savedIcon.addClass('press');
+      continue; 
+    }
```
Comment (wjiamin) [inline where-to-travel/src/main/webapp/script.js]: Inline "} else {"

File: where-to-travel/src/main/webapp/script.js [hunk 10]
```diff
@@ -447,46 +502,72 @@ function populatePlaces(placeArray) {
       focusedCard.scrollIntoView({behavior: 'smooth', block: 'center'});
     });
 
-    placeMarker.addListener('mouseover', function () {
-      placeMarker.setIcon(SELECTED_PIN_PATH);
-    });
+      placeMarker.addListener('mouseover', function () {
```
Comment (wjiamin) [inline where-to-travel/src/main/webapp/script.js:507]: Undo these indentation changes? I believe they were originally aligned.

File: where-to-travel/src/main/webapp/script.js [hunk 11]
```diff
@@ -447,46 +502,72 @@ function populatePlaces(placeArray) {
...
-        link: link,
-        time: time,
+        timeAsString: time,
+        timeInSeconds: card.getAttribute('data-timeInSeconds'),
+        place_id: placeId,
       }
       ref.set(data);
+      let lat = card.dataset.lat;
+      let lng = card.dataset.lng;
+      var ref = firebase.database().ref('users/' + firebase.auth().currentUser.uid + '/places/' + name + '/geometry/location/');
```
Comment (wjiamin) [inline where-to-travel/src/main/webapp/script.js]: ref = ref + '/geometry/location/'?

File: where-to-travel/src/main/webapp/script.js [hunk 12]
```diff
@@ -447,46 +502,72 @@ function populatePlaces(placeArray) {
...
       var data = {
         name: name,
-        link: link,
-        time: time,
+        timeAsString: time,
+        timeInSeconds: card.getAttribute('data-timeInSeconds'),
+        place_id: placeId,
       }
       ref.set(data);
+      let lat = card.dataset.lat;
```
Comment (wjiamin) [inline where-to-travel/src/main/webapp/script.js:543]: Add a comment to this block similar to above?

File: where-to-travel/src/main/webapp/script.js [hunk 13]
```diff
@@ -497,27 +578,38 @@ function populatePlaces(placeArray) {
...
+       placeId="${place_id}" 
+       placeName="${name}" 
+       style="margin-right: 0;">
       <div class="card-body">
         <h5 class="card-title">${name}
-        <span class="icon" id="${iconId}">
-          &#9733
-        <span>
+          <span class="icon" id="${iconId}">
+            &#9733
```
Comment (wjiamin) [inline where-to-travel/src/main/webapp/script.js]: Add semicolon?

File: where-to-travel/src/main/webapp/style.css [hunk 14]
```diff
@@ -232,4 +232,66 @@ h5 {
     max-width: 45%;
     padding: 0;
   }
+}
+
+.switch {
+  position: relative;
```
Comment (wjiamin) [inline where-to-travel/src/main/webapp/style.css]: Alphabetize declarations.

File: where-to-travel/src/main/webapp/script.js (hunk 5 above)
Comment (andy7809) [reply where-to-travel/src/main/webapp/script.js]: fixed with 7030b97

File: where-to-travel/src/main/webapp/script.js (hunk 7 above)
Comment (andy7809) [reply where-to-travel/src/main/webapp/script.js]: That was an old comment, I removed it in 54cc36c

File: where-to-travel/src/main/webapp/script.js (hunk 8 above)
Comment (andy7809) [reply where-to-travel/src/main/webapp/script.js]: Fixed with 5e15270

File: where-to-travel/src/main/webapp/script.js (hunk 6 above)
Comment (andy7809) [reply where-to-travel/src/main/webapp/script.js]: Fixed 80e3c5f

File: where-to-travel/src/main/webapp/script.js (hunk 10 above)
Comment (andy7809) [reply where-to-travel/src/main/webapp/script.js:507]: fixed in d6b47d2

File: where-to-travel/src/main/webapp/script.js (hunk 9 above)
Comment (andy7809) [reply where-to-travel/src/main/webapp/script.js]: fixed in d6b47d2

File: where-to-travel/src/main/webapp/script.js (hunk 10 above)
Comment (andy7809) [reply where-to-travel/src/main/webapp/script.js:507]: no it isnt, i made a mistake

Comment (andy7809) [reply where-to-travel/src/main/webapp/script.js:507]: fixed in c5463ef

File: where-to-travel/src/main/webapp/script.js (hunk 11 above)
Comment (andy7809) [reply where-to-travel/src/main/webapp/script.js]: @emmapaczkowski could we get your input / fix here?

File: where-to-travel/src/main/webapp/script.js (hunk 12 above)
Comment (andy7809) [reply where-to-travel/src/main/webapp/script.js:543]: @emmapaczkowski could you do this one?

File: where-to-travel/src/main/webapp/script.js (hunk 13 above)
Comment (andy7809) [reply where-to-travel/src/main/webapp/script.js]: fixed with e9123ae

File: where-to-travel/src/main/webapp/script.js (hunk 11 above)
Comment (emmapaczkowski) [reply where-to-travel/src/main/webapp/script.js]: done

File: where-to-travel/src/main/webapp/script.js (hunk 12 above)
Comment (emmapaczkowski) [reply where-to-travel/src/main/webapp/script.js:543]: done

File: where-to-travel/src/main/webapp/style.css (hunk 14 above)
Comment (andy7809) [reply where-to-travel/src/main/webapp/style.css]: fixed with 11b56aa

Comment (emmapaczkowski) [reply where-to-travel/src/main/webapp/style.css]: done

File: where-to-travel/src/main/webapp/script.js [hunk 15]
```diff
@@ -414,79 +453,125 @@ function populatePlaces(placeArray) {
...
+        lng: lng
       }
       ref.set(data);
+      savedPlacesSet.add(placeId);
     } else if (firebase.auth().currentUser && (!$(this).hasClass('press'))) {
-      const name = $(this).parent().parent().parent().attr('placeName');
-       // Delete user saved places when the star is not pressed
-      var ref = firebase.database().ref('users/' + firebase.auth().currentUser.uid + '/' + 'places' + '/' + name);
+      // Delete user saved places when the star is not pressed/unpressed
+      var ref = firebase.database().ref('users/' + firebase.auth().currentUser.uid + '/places/' + name);
```
Comment (saileshsimhadri) [inline where-to-travel/src/main/webapp/script.js:554]: This url seems to be used frequently. Would it be worth turning into a function?

File: where-to-travel/src/main/webapp/script.js [hunk 16]
```diff
@@ -348,17 +362,41 @@ function addLoginButtons() {
...
   $('#' + DASH_ID).append(dashElement);
 }
 
-/** Toggle the focused pin/card off */
+/**
+ * Toggle the focused pin/card off
+ */
 function toggleFocusOff() {
-  if(focusedCard != null) {
+  if (focusedCard != null) {
```
Comment (saileshsimhadri) [inline where-to-travel/src/main/webapp/script.js:399]: remove extra space

**Review by saileshsimhadri — COMMENTED** [review]
LGTM

File: where-to-travel/src/main/webapp/script.js (hunk 16 above)
Comment (emmapaczkowski) [reply where-to-travel/src/main/webapp/script.js:399]: done
